.catalog:
  name: "Adhoc Traefik Global con Redis"
  version: "2.2.8"
  description: "Traefik Load Balancer."
  minimum_rancher_version: v1.3.2
  questions:

    # Configuration

    - variable: "domain"
      description: "Can be overridden by setting the 'traefik.domain' label on an service."
      label: "Default domain used:"
      required: true
      default: "example.com"
      type: "string"

    - variable: "http_port"
      description: "Traefik http public port to listen."
      label: "Http port:"
      required: true
      default: 80
      type: "int"

    - variable: "https_port"
      description: "Traefik https public port to listen."
      label: "Https port:"
      required: true
      default: 443
      type: "int"

    - variable: "EnableServiceHealthFilter"
      label: "Enable Service Health Filter:"
      required: false
      # por ahora sugerimos que si si no da error al restaurar backups. Luego, si queremos actualizar online, tal vez tengamos que desactivarlo
      default: true
      type: "boolean"

    # Administration Panel

    - variable: "admin_domain"
      description: "Domain for the administration panel"
      label: "Treafik Administration Domain:"
      required: true
      default: "tr.example.com"
      type: "string"

    - variable: "auth_users"
      label: "Traefik Administration Users:"
      description: "CSV format: User:Hash,User:Hash. Administration panel is on tr.{domain}. You can generate in here https://www.web2generators.com/apache-tools/htpasswd-generator"
      required: false
      type: "string"

      # Configuration Storage

    - variable: "ConsulEndpoint"
      label: "Consul Endpoint:"
      required: false
      default: "consul.infra-consul:8500"
      type: "string"

    - variable: "RedisEndpoint"
      label: "Redis Endpoint:"
      required: false
      default: "redis.infra-redis:6379"
      type: "string"

    - variable: "RedisPassword"
      label: "Redis Password:"
      required: false
      type: "string"

      # Certificate Resolvers

    - variable: "acme_email"
      description: "ACME user email."
      label: "ACME email:"
      required: true
      default: "test@traefik.io"
      type: "string"

    - variable: "acme_dns_challenge_GCE_PROJECT"
      label: "Gcloud DNS challenge GCE_PROJECT"
      type: "string"

    - variable: "acme_dns_challenge_GCE_SERVICE_ACCOUNT_FILE"
      label: "Gcloud DNS challenge GCE_SERVICE_ACCOUNT_FILE"
      type: "string"

    - variable: "acme_dns_challenge_CF_API_KEY"
      label: "Cloudflare DNS challenge CF_API_KEY"
      type: "string"

    - variable: "acme_dns_challenge_CF_API_EMAIL"
      label: "Cloudflare DNS challenge CF_API_EMAIL"
      type: "string"

      # Rancher

    - variable: "host_label"
      description: "Host label where to run traefik service."
      label: "Host label:"
      required: true
      default: "traefik_lb=true"
      type: "string"

#
# Scaling and health checks per service as per docker-compose.yml
#

version: 2
services:
  traefik:
    retain_ip: true
    health_check:
      port: 8080
      interval: 5000
      unhealthy_threshold: 3
      request_line: 'GET /dashboard/# HTTP/1.0'
      healthy_threshold: 2
      response_timeout: 5000
